### ISSUE TITLE
Bug: @pixi/react v.7.1.0 is not working with React v.17.0.2

### ISSUE THREAD

**Issue by uichleba** [pixijs/pixi-react#435]
### Current Behavior

Cannot read properties of undefined (reading 'current')
TypeError: Cannot read properties of undefined (reading 'current')
    at ensureRootIsScheduled (http://localhost:3000/static/js/bundle.js:17203:40)
    at scheduleUpdateOnFiber (http://localhost:3000/static/js/bundle.js:17105:11)
    at Object.updateContainer (http://localhost:3000/static/js/bundle.js:20011:11)
    at Stage.componentDidMount (http://localhost:3000/static/js/bundle.js:21324:17)
    at commitLifeCycles (http://localhost:3000/static/js/bundle.js:48463:28)
    at commitLayoutEffects (http://localhost:3000/static/js/bundle.js:50809:11)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:34158:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:34202:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:34257:35)
    at commitRootImpl (http://localhost:3000/static/js/bundle.js:50580:13)

### Expected Behavior

Working without error.

### Steps to Reproduce

- npx create-react-app test --template typescript
- change versions of react & react-dom to `17.0.2`
- craete new component with `< Stage >< Text text="hi" /></Stage>`

Observe the error.

### Environment

- **`@pixi/react` version**: *e.g. 7.1.0*
- **`pixi.js` version**: *e.g. 7.2.4*
- **`React` version**: *e.g. 17.0.2*
- **`ReactDOM` version**: *e.g. 17.0.2*
- **Browser & Version**: *e.g. Chrome 108*
- **OS & Version**: *e.g. MacOS*

**Comment by polimorficzny** [comment]
Having the same issue when trying to update from v5. @uichleba have you found some workarounds maybe?

**Comment by uichleba** [comment]
@polimorficzny I just used old version of pixi-react v6.8.0. That work just fine until we upgrade react & react-dom to v18.2.0

**Comment by met5678** [comment]
Same issue here but with React v17.0.1

**Comment by lunarraid** [comment]
Unfortunately the fiber reconciler upgrades are not compatible with React < 18. You will need to use React 18 or above going forward. It is unlikely this will change.
