### ISSUE TITLE
Bug: Does not work with Latest Nextjs: ReferenceError: window is not defined

### ISSUE THREAD

**Issue by himrocks33** [pixijs/pixi-react#454]
### Current Behavior

When attempting to build Nextjs application with `yarn build` an error is received from any component/page that uses pixi-react components or hooks.   

Full Error: 

> Error occurred prerendering page "/floor-plan". Read more: https://nextjs.org/docs/messages/prerender-error
ReferenceError: window is not defined
    at C:\git\sos-web\.next\server\chunks\3420.js:24927:44761
    at C:\git\sos-web\.next\server\chunks\3420.js:24927:22
    at Object.59042 (C:\git\sos-web\.next\server\chunks\3420.js:24927:90)
    at __webpack_require__ (C:\git\sos-web\.next\server\webpack-runtime.js:25:43)
    at Object.64361 (C:\git\sos-web\.next\server\chunks\8434.js:1302:25)
    at __webpack_require__ (C:\git\sos-web\.next\server\webpack-runtime.js:25:43)
    at Module.51019 (C:\git\sos-web\.next\server\app\(main)\floor-plan\page.js:476:18)
    at __webpack_require__ (C:\git\sos-web\.next\server\webpack-runtime.js:25:43)
    at M (C:\git\sos-web\node_modules\next\dist\compiled\react-server-dom-webpack\cjs\react-server-dom-webpack-client.edge.production.min.js:24:46)
    at ma (C:\git\sos-web\node_modules\next\dist\compiled\react-server-dom-webpack\cjs\react-server-dom-webpack-client.edge.production.min.js:28:324)

### Expected Behavior

I would expect to be able to use Nextjs and pixi-react in a project.  Nextjs is probably the most used react toolchain now so I would assume pixi-react should support using nextjs to build a project.

### Steps to Reproduce

- create a brand new nextjs application
- add pixi-react
- add pixi-react components to the application
- attempt `yarn build`
- see error

### Environment

- **`next` version**: 13.4.13
- **`@pixi/react` version**: 7.1.0
- **`pixi.js` version**: 7.2.4
- **`React` version**: 18.2.0
- **`ReactDOM` version**: 18.2.0

### Possible Solution

It seems pixi react is using window somewhere in the code base that needs to be checked to see if you are on the server or on client:

`if (typeof window !== "undefined") { /* we're on the client*/ }`

**Comment by lunarraid** [comment]
This is caused by server code importing client-only code. To make sure that PixiJS (and any of its libraries) are running solely on the client, make sure to use dynamic imports.

https://nextjs.org/docs/pages/building-your-application/optimizing/lazy-loading#nextdynamic
