### ISSUE TITLE
Bug: React$1.Component is not a constructor

### ISSUE THREAD

**Issue by HammerTWang** [pixijs/pixi-react#461]
### Current Behavior

npm run dev

> myapp@0.1.0 dev
> next dev

  ▲ Next.js 13.5.5
  - Local:        http://localhost:3000

 ✓ Ready in 2.2s
 ○ Compiling /page ...

warn - No utility classes were detected in your source files. If this is unexpected, double-check the `content` option in your Tailwind CSS configuration.
warn - https://tailwindcss.com/docs/content-configuration
 ✓ Compiled /page in 4.7s (758 modules)
 ⨯ node_modules/@pixi/react/dist/index.cjs-dev.js (6618:23) @ $$$reconciler
 ⨯ TypeError: React$1.Component is not a constructor
    at __webpack_require__ (/Users/TW/IdeaProjects/myapp/.next/server/webpack-runtime.js:33:42)
    at eval (./src/app/page.js:7:69)
    at (rsc)/./src/app/page.js (/Users/TW/IdeaProjects/myapp/.next/server/app/page.js:173:1)
    at Function.__webpack_require__ (/Users/TW/IdeaProjects/myapp/.next/server/webpack-runtime.js:33:42)
    at async Promise.all (index 0)
null
 ⨯ node_modules/@pixi/react/dist/index.cjs-dev.js (6618:23) @ $$$reconciler
 ⨯ TypeError: React$1.Component is not a constructor
    at __webpack_require__ (/Users/TW/IdeaProjects/myapp/.next/server/webpack-runtime.js:33:42)
    at eval (./src/app/page.js:7:69)
    at (rsc)/./src/app/page.js (/Users/TW/IdeaProjects/myapp/.next/server/app/page.js:173:1)
    at Function.__webpack_require__ (/Users/TW/IdeaProjects/myapp/.next/server/webpack-runtime.js:33:42)
    at async Promise.all (index 0)
digest: "4204431394"
null
 ⨯ node_modules/@pixi/react/dist/index.cjs-dev.js (6618:23) @ $$$reconciler
 ⨯ TypeError: React$1.Component is not a constructor
    at __webpack_require__ (/Users/TW/IdeaProjects/myapp/.next/server/webpack-runtime.js:33:42)
    at eval (./src/app/page.js:7:69)
    at (rsc)/./src/app/page.js (/Users/TW/IdeaProjects/myapp/.next/server/app/page.js:173:1)
    at Function.__webpack_require__ (/Users/TW/IdeaProjects/myapp/.next/server/webpack-runtime.js:33:42)
null
TypeError: React$1.Component is not a constructor
    at $$$reconciler (webpack-internal:///(rsc)/./node_modules/@pixi/react/dist/index.cjs-dev.js:5499:35)
    at eval (webpack-internal:///(rsc)/./node_modules/@pixi/react/dist/index.cjs-dev.js:19304:17)
    at (rsc)/./node_modules/@pixi/react/dist/index.cjs-dev.js (/Users/TW/IdeaProjects/myapp/.next/server/vendor-chunks/@pixi.js:2250:1)
    at __webpack_require__ (/Users/TW/IdeaProjects/myapp/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///(rsc)/./src/app/page.js:7:69)
    at (rsc)/./src/app/page.js (/Users/TW/IdeaProjects/myapp/.next/server/app/page.js:173:1)
    at Function.__webpack_require__ (/Users/TW/IdeaProjects/myapp/.next/server/webpack-runtime.js:33:42)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:540:9)
    at process.processTimers (node:internal/timers:514:7)
    at async ek (/Users/TW/IdeaProjects/myapp/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:11:455639)
    at async eJ (/Users/TW/IdeaProjects/myapp/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:11:459729)
    at async eY (/Users/TW/IdeaProjects/myapp/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:11:460204)
    at async eY (/Users/TW/IdeaProjects/myapp/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:11:460335)
    at async eK (/Users/TW/IdeaProjects/myapp/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:11:463747)
    at async /Users/TW/IdeaProjects/myapp/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:11:464225 {
  digest: '3118112480'
}
 ⨯ node_modules/@pixi/react/dist/index.cjs-dev.js (6618:23) @ $$$reconciler
 ⨯ TypeError: React$1.Component is not a constructor
    at $$$reconciler (webpack-internal:///(rsc)/./node_modules/@pixi/react/dist/index.cjs-dev.js:5499:35)
    at eval (webpack-internal:///(rsc)/./node_modules/@pixi/react/dist/index.cjs-dev.js:19304:17)
    at (rsc)/./node_modules/@pixi/react/dist/index.cjs-dev.js (/Users/TW/IdeaProjects/myapp/.next/server/vendor-chunks/@pixi.js:2250:1)
    at __webpack_require__ (/Users/TW/IdeaProjects/myapp/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///(rsc)/./src/app/page.js:7:69)
    at (rsc)/./src/app/page.js (/Users/TW/IdeaProjects/myapp/.next/server/app/page.js:173:1)
    at Function.__webpack_require__ (/Users/TW/IdeaProjects/myapp/.next/server/webpack-runtime.js:33:42)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:540:9)
    at process.processTimers (node:internal/timers:514:7)
    at async ek (/Users/TW/IdeaProjects/myapp/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:11:455639)
    at async eJ (/Users/TW/IdeaProjects/myapp/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:11:459729)
    at async eY (/Users/TW/IdeaProjects/myapp/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:11:460204)
    at async eY (/Users/TW/IdeaProjects/myapp/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:11:460335)
    at async eK (/Users/TW/IdeaProjects/myapp/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:11:463747)
    at async /Users/TW/IdeaProjects/myapp/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:11:464225 {
  digest: '3118112480',
  page: '/'
}
null
 ⚠ Fast Refresh had to perform a full reload due to a runtime error.
 ✓ Compiled /_error in 206ms (900 modules)
 ⚠ Fast Refresh had to perform a full reload due to a runtime error.
 ✓ Compiled /favicon.ico/route in 174ms (605 modules)

### Expected Behavior

It should be work.

### Steps to Reproduce

1. I create a new next app
`npx create-next-app`

2. Install pixi.js and @pixi/react
`npm install pixi.js @pixi/react`

3. I change the page.js as following:
`
  import { Stage, Container, Sprite } from '@pixi/react' 
  export default function Home() {
    return (
      <Stage width={800} height={600}>
        <Container>
          <Sprite image="https://s3-us-west-2.amazonaws.com/s.cdpn.io/693612/IaUrttj.png" x={100} y={100} />
        </Container>
      </Stage>
    )
  }
`

### Environment

"@pixi/react": "^7.1.1",
"next": "13.5.5",
"pixi.js": "^7.3.1",
"react": "^18",
"react-dom": "^18"

### Additional Information

It works if I remove next.js. Anyone can help?

**Comment by HammerTWang** [comment]
I add 'use client' and it fixed.
